travis:
  secure:
    BINSTAR_TOKEN: p77SYnZm+1oBRezSQXl6hH916yoA2GjQXyIcBi3x47eKwmzhBP4bMcU4BgjD7Utyo0fQtNr6wLu4zg73koPo1IWJV9uAxsMuqYhZyHmoD6lMwp8Ql2x/PX1NChpSwKgggdr1+dTRR1l8CpGbHqCVuLqDgEd6W8SEIwS8RzuKM0u1yf8OjQ61TTAB8CZg0U3KIWGE5tq2WQ99adFAah0TneBKf3FmOtvPIqhKF1l0bAvws53o1t02JcLRl5NfKDb/sqUyXzof3LYLRZoDeaz3PWC0iDhSyA9eNyPGs4HXk6FACjyGL1sgEJ5GDI5eMTePX6ltTAOgGIekkbbexddf2pfqK2PPyKaFOMkaLo/Io//XOAB9G1plvSyDJlFTLwek6IVIelaEyZP8zxakUAFleqqSZY/EPSICWX9aGW8Nk6GM8R9/iYXWENjIS9lBAnd8jD0ph8r38n3kEUpbxVoZddxgHEDO21Lka+b//WeyQ05RqRNBmlaKSNJgfQDkDb6UGR1MYdqzgEpoyxqnHN+OoTH12dE3jY/oIhNdK2i7eL7frjaqLV97Hox6Qal899pg2/0EGmEOZKUs+OjYd3/nMJpBcIBfxJlT+ZpGWo4GKB7M/Er53bZzNRpGF4WXjHd8+LtNZSHPY7mRXAqtpd9Zom/ivknXomH1XnhcRjmtIic=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
