travis:
  secure:
    BINSTAR_TOKEN: sa6ZaPpVUhTVo5KjRFCez8G77iMp2uPzbLCFddAxEWsoTMl2FSAH5QdUEliLuUWgcN5JJOAgN1ezT0QGs3ChThd5bu68Lsrvi1QNwuXKDaY0kWO0lclTLloO0BXchlfUCEQpTG+B/KaXqrj1A4qF6zZNpgGleYcXMIk5LH2jhgz+OpduX7q2NoAcZHApzh6pZnuhZLmdKuguIjF1CTY2KWaOuubkmyiOkupdvCMHnl+pRUjnIzxLnIpGlyOmlyQxU4SwGl4OY36eQdlmvi5AE5Y9/VhrS779Uqb/AcOXQE1iDcREwiYP5Jk0gDyoHR4LODlOWgnsSh0AC7gsrZaUnbzfopQ94E9CLwL2BIeLBx0TLNaCmjUJ60tX1Lcc1C8n+fKmpJ4TKKhGGuKK8/GajdyS9y+ZjfaVEyelf96+qwasI/64/3ph/x2V+CIFRbUc7Fx1EQKEA7STwILiwL5TN3Rcd+6DT95OQykl2EaLZTk7xjo3bwPDCX9nypEkwdG8Sffyqf4YKCBwOSdI2cYJrOlLJqHZvdVYnMmUkRloj99Pz0c9l2fBR7rJDh3suhDjvnCRLNz4gsWRlIGxciP0BeQSD3CfT9hb1uG9o3VF9wqfWtyDtnFrSdYylHDQGNpVoUUcRfcaCo0xFYiSNpd0ZIYQiwaid1hKkxA8r1Ehk+I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
